apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: play1
  labels:
    app: nginx    
    version: v1    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v1
  template:
    metadata:
      labels:
        app: nginx
        version: v1 
        a: harish
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80     

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: play1
  labels:
    app: nginx
    service: nginx
spec:
  selector:
    app: nginx    
  ports:
    - port: 80      
      name: http	

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: my-v-service
  namespace: play1
spec:
  hosts:
    - "*"
  gateways:
    - mygateway
  http:
  - match:
    - uri:
        prefix: /mlflow
    rewrite:
      uri: /
    route:
    - destination:
        host: nginx.play1.svc.cluster.local
        port:
          number: 80

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: mygateway
  namespace: play1
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"